const String bearerToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE1NzI4MzIsInVzZXJfaWQiOiJiZDA1ZmQ1NC1iZGEwLTRlZmMtOTdjNi1kMDViZThhOGQ5MzMiLCJhdmF0YXIiOm51bGx9.FHrBzX6gKY9aHCbxPg-k5X00blzofM_7tQyiwVXK5ZY';
const String baseUrl = 'https://chatter-backend-dev.azurewebsites.net/api/v1';
